version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - my_app_network
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  
  backend:
    build:
      context: ./backend  
    container_name: backend
    networks:
      - my_app_network
    volumes:
      - backend_data:/app/backend
    ports:
      - "80:80"
    environment:
      MONGO_URL: mongodb://mongodb:27017/course-goals

  frontend:
    build:
      context: ./frontend 
    container_name: frontend
    networks:
      - my_app_network
    ports:
      - "3000:3000"

networks:
  my_app_network:
    driver: bridge

volumes:
  mongo_data:
  backend_data:
