apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-declarative
      tier: frontend
  template:
    metadata:
      labels:
        app: app-declarative
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: jmbp75/iacd_pl4
        ports: 3000