apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: app-declarative
    tier: mongo
  ports:
    - protocol: 'TCP'
      port: 27017
      targetPort: 27017
  type: ClusterIP