version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - my_app_network
    volumes:
      - mongo_data:/data/db
  
  backend:
    build:
      context: ./backend  
    networks:
      - my_app_network
    volumes:
      - backend_data:/app/backend
    ports:
      - "80:80"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend 
    networks:
      - my_app_network
    ports:
      - "3000:3000"

networks:
  my_app_network:
    driver: bridge

volumes:
  mongo_data:
  backend_data:
